# Generated by Django 5.1.1 on 2024-10-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photos/blogs/",
                        verbose_name="Изображение",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Publication flag"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Укажите количество просмотров",
                        verbose_name="Количество просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
                "ordering": ["title"],
            },
        ),
    ]
