# Generated by Django 5.1.1 on 2024-10-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos/", verbose_name="Изображение"
            ),
        ),
    ]
