# Generated by Django 4.2.2 on 2024-10-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("can_unpublish_product", "can unpublish product"),
                    ("can_delete_product", "can delete product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="unpublish",
            field=models.BooleanField(default=False, verbose_name="Статус публикации"),
        ),
    ]
