# Generated by Django 4.2.2 on 2024-10-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_options_product_unpublish"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("can_unpublish_product", "can unpublish product"),
                    ("can_edit_description", "can edit description"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.RenameField(
            model_name="product",
            old_name="unpublish",
            new_name="publication_status",
        ),
    ]
